# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b754134f7996755c0097e703fc05cb46deff8872365e80547917a188d3722e65b9c2e449b0945e442d04ba7ab5fc1137e00f8cf7e26a0afaf3b9e314646135c1

test:
  secret_key_base: 8dce354d63b2720880545620a6b5938e300fbd9e8b44f8e8856129aa632247fa067da6bd97d61f5c28b0aaa9e096fde2d3b8a105d25471b643aac210b2d3b37e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
